@CodeBaseService_HostAddress = http://localhost:5002

POST {{CodeBaseService_HostAddress}}/code-base/all
Content-Type: application/json
Accept: application/json

{
  "paginationQuery": {
    "pageNumber": 1,
    "pageSize": 10
  }
}

###

GET {{CodeBaseService_HostAddress}}/code-base/by-user-id/123e4567-e89b-12d3-a456-426614174003
Content-Type: application/json
Accept: application/json

{
}

###

POST {{CodeBaseService_HostAddress}}/code-base/add
Content-Type: application/json
Accept: application/json

{
  "userId": "355e4567-e89b-12d3-a456-426614174000",
  "name": "My new codebase",
  "supportedPlatform": 1,
  "valid": false
}

### Get existing id

GET {{CodeBaseService_HostAddress}}/code-base/123e4567-e89b-12d3-a456-426614174004
Accept: application/json

### Get non existing id not found

GET {{CodeBaseService_HostAddress}}/code-base/123e4567-e89b-12d3-a456-426614174001
Accept: application/json

###

PATCH {{CodeBaseService_HostAddress}}/code-base/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json
Accept: application/json

{
  "status": 1
}
