@UsersService_HostAddress = http://localhost:5127

POST {{UsersService_HostAddress}}/users
Content-Type: application/json
Accept: application/json

{
  "paginationQuery": {
    "pageNumber": 1,
    "pageSize": 10,
    "filterParams": {
      "Language": "Spanish"
    }
  }
}

###

POST {{UsersService_HostAddress}}/users
Content-Type: application/json
Accept: application/json

{
  "UserName": "jdoe",
  "Email": "jdoe@example.com",
  "Name": "John Doe",
  "Language": "English"
}

###

GET {{UsersService_HostAddress}}/users/123e4567-e89b-12d3-a456-426614174000
Accept: application/json

###

PATCH {{UsersService_HostAddress}}/users/c906787c-1ae0-45cc-a1d4-736e724b194f
Content-Type: application/json
Accept: application/json

{
  "Email": "updatedemail@example.com",
  "Name": "Updated Name",
  "Language": "Updated Language"
}
