# Use the official .NET 8 SDK image as the build image
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Log the current step
RUN echo "Step 1: Copying the csproj file and restoring dependencies"

# Copy the project files and restore dependencies as distinct layers
COPY ../CodeExecutionService/CodeExecutionService.csproj ./CodeExecutionService/
COPY ../ExternalDomainEntities/ExternalDomainEntities.csproj ./ExternalDomainEntities/
COPY ../Generics/Generics.csproj ./Generics/

RUN dotnet restore ./CodeExecutionService/CodeExecutionService.csproj

# Log the current step
RUN echo "Step 2: Copying the remaining source code and building the application"

# Copy the remaining source code and build the application
COPY ../CodeExecutionService/ ./CodeExecutionService/
COPY ../ExternalDomainEntities/ ./ExternalDomainEntities/
COPY ../Generics ./Generics

RUN dotnet publish ./CodeExecutionService/CodeExecutionService.csproj -c Release -o out

# Log the current step
RUN echo "Step 3: Using the official .NET runtime image as the base runtime image"

# Use the official .NET runtime image as the base runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Log the current step
RUN echo "Step 4: Copying the published output from the build environment"

COPY --from=build-env /app/out .

# Log the current step
RUN echo "Step 5: Setting the entry point for the application"

# Set the entry point for the application
ENTRYPOINT ["dotnet", "CodeExecutionService.dll"]
