services:
  postgres-integration-testing:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_integration_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - development-network
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - development-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - development-network

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    networks:
      - development-network

  code-run-service:
    build:
      context: ..
      dockerfile: ./Configs/dockerfile-template
      args:
        SERVICE_NAME: ${SERVICE1_NAME}
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SERVICE_NAME: ${SERVICE1_NAME}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT_INNER}
      DB_NAME: ${SERVICE1_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    ports:
      - "5001:8080"
    networks:
      - development-network

  code-base-service:
    build:
      context: ..
      dockerfile: ./Configs/dockerfile-template
      args:
        SERVICE_NAME: ${SERVICE2_NAME}
    depends_on:
      - postgres
      - rabbitmq
      - mongo
    environment:
      SERVICE_NAME: ${SERVICE2_NAME}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT_INNER}
      DB_NAME: ${SERVICE2_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT_INNER}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "5002:8080"
    networks:
      - development-network

  user-service:
    build:
      context: ..
      dockerfile: ./Configs/dockerfile-template
      args:
        SERVICE_NAME: ${SERVICE3_NAME}
    depends_on:
      - postgres
    environment:
      SERVICE_NAME: ${SERVICE3_NAME}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT_INNER}
      DB_NAME: ${SERVICE3_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5003:8080"
    networks:
      - development-network

  code-formater-service:
    build:
      context: ..
      dockerfile: ./Configs/dockerfile-formater
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    ports:
      - "5004:8080"
    networks:
      - development-network
  
  code-execution-engine:
    build:
      context: ..
      dockerfile: ./Configs/dockerfile-execution
    depends_on:
      - rabbitmq
      - mongo
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT_INNER}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "5005:8080"
    networks:
      - development-network

volumes:
  rabbitmq_data:
  postgres_data:
  postgres_integration_data:
  mongo_data:

networks:
  development-network:
    driver: bridge
