@UsersService_HostAddress = http://localhost:5127

###

POST {{UsersService_HostAddress}}/user/all
Content-Type: application/json
Accept: application/json

{
  "paginationQuery": {
    "pageNumber": 1,
    "pageSize": 10
  }
}

###

GET {{UsersService_HostAddress}}/user/all
Content-Type: application/json
Accept: application/json

{
  "paginationQuery": {
    "pageNumber": 1,
    "pageSize": 10,
    "filterParams": {
      "Language": "Spanish"
    }
  }
}

###

POST {{UsersService_HostAddress}}/user/add
Content-Type: application/json
Accept: application/json

{
  "UserName": "jdoe",
  "Password": "Test",
  "Email": "jdoe@example.com",
  "Name": "John Doe",
  "Language": "English"
}

### Get existing id

GET {{UsersService_HostAddress}}/user/123e4567-e89b-12d3-a456-426614174003
Accept: application/json

### Get non existing id not found

GET {{UsersService_HostAddress}}/user/123e4567-e89b-12d3-a456-426614174001
Accept: application/json

###

PATCH {{UsersService_HostAddress}}/user/c906787c-1ae0-45cc-a1d4-736e724b194f
Content-Type: application/json
Accept: application/json

{
  "Email": "updatedemail@example.com",
  "Name": "Updated Name",
  "Language": "Updated Language"
}
