name: Build, Push Docker Image, and Deploy via Terraform

on:
  push:
    tags:
      - 'v*'  # Trigger this workflow when a version tag is pushed

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get the version from the tag
        id: vars
        run: echo "APP_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.REGION }} | docker login --username AWS --password-stdin 376129885232.dkr.ecr.${{ secrets.REGION }}.amazonaws.com
          
      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names test-api || \
          aws ecr create-repository --repository-name test-api

      - name: Build Docker image and push to ECR
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64 --build-arg APP_VERSION=${{ env.APP_VERSION }} \
            -t 376129885232.dkr.ecr.${{ secrets.REGION }}.amazonaws.com/test-api:${{ env.APP_VERSION }} \
            -f InfrastructureTestCode/Dockerfile InfrastructureTestCode --push

  terraform:
    needs: build
    environment: staging
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      # Pass AWS credentials as environment variables to Terraform
      - name: Initialize Terraform AWS
        working-directory: MulticloudInfra/aws  # Adjust path to your Terraform files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.REGION }}
        run: |
          cd MulticloudInfra/aws
          terraform init
    
      
      # Run import script before Terraform apply
      - name: Run Import Script
        run: |
          cd MulticloudInfra/aws
          chmod +x import_resources.sh
          ./import_resources.sh

      - name: Plan Terraform AWS
        working-directory: MulticloudInfra/aws  # Adjust path to your Terraform files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.REGION }}
        run: terraform plan -out=tfplan

      - name: Apply Terraform Changes
        working-directory: MulticloudInfra/aws  # Adjust path to your Terraform files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.REGION }}
        run: terraform apply -auto-approve tfplan
