name: Build and Deploy to AWS

on:
  push:
    tags:
      - 'v*'  # This triggers the workflow on tags starting with "v", like "v1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get the version from the tag
        id: vars
        run: echo "APP_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 376129885232.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build --build-arg APP_VERSION=${{ env.APP_VERSION }} -t my-dotnet-api:${{ env.APP_VERSION }} .
          docker tag my-dotnet-api:${{ env.APP_VERSION }} 376129885232.dkr.ecr.us-east-1.amazonaws.com/my-dotnet-api:${{ env.APP_VERSION }}

      - name: Push Docker image to ECR
        run: |
          docker push 376129885232.dkr.ecr.us-east-1.amazonaws.com/my-dotnet-api:${{ env.APP_VERSION }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 376129885232.dkr.ecr.us-east-1.amazonaws.com

      - name: Update ECS service with the new image
        run: |
          aws ecs update-service \
            --cluster my-dotnet-cluster \
            --service my-dotnet-service \
            --force-new-deployment \
            --region us-east-1